### ISSUE TITLE
Cannot run under Windows

### ISSUE THREAD

**Issue by wiseman13** [rupert/pandora-to-google-music#4]
I was able to get all of the dependencies installed, but I get the following error when running the script. Any ideas?

C:\pandora-to-google-music-master>python pandora_to_google
_music.py
Traceback (most recent call last):
  File "pandora_to_google_music.py", line 9, in <module>
    from gmusicapi import Mobileclient
ImportError: cannot import name Mobileclient

**Comment by wiseman13** [comment]
Anyone have any ideas on this?

**Comment by rupert** [comment]
I don't have a Windows machine to test this on, so I used a [Windows 7 VM](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/).

* Install [Python 2](https://www.python.org/downloads/windows/).
* Install [Git](https://git-scm.com/download/win).
* Add `C:\Python27` and `C:\Python27\Scripts` to the `PATH`.

Install `virtualenv`:

```
C:\>pip install virtualenv
```

Check versions:

```
C:\>python --version
Python 2.7.12
C:\>git --version
git version 2.10.0.windows.1
C:\>pip --version
pip 8.1.1 from c:\python27\lib\site-packages (python 2.7)
C:\>virtualenv --version
15.0.3
```

Download and run:

```
C:\>git clone https://github.com/rupert/pandora-to-google-music.git
C:\>cd pandora-to-google-music
C:\pandora-to-google-music>virtualenv venv
C:\pandora-to-google-music>.\venv\Scripts\activate.bat
(venv) C:\pandora-to-google-music>pip install -r requirements.txt
(venv) C:\pandora-to-google-music>python pandora_to_google_music.py
```

Hopefully those steps work for you too :smile:
