### ISSUE TITLE
Playlists in GPM are empty

### ISSUE THREAD

**Issue by fox365** [rupert/pandora-to-google-music#6]
I have used this tool once before and it worked perfectly. When I attempted this time i was getting some syntax errors that led me to updating to tensorflow 0.5 which helped everything get going. At first it failed with a "Too many Items" error and it emptied out my playlists from before. I thought I was running into an issue of too many songs in a playlist, and I am not sure if this script was capable of avoiding duplicates. 

I deleted all the Pandora based playlists and started the script again, it ran fine for what I can see but it created the blank playlists again. 
![pandora rupert](https://cloud.githubusercontent.com/assets/582275/23934575/84a9445c-0903-11e7-9151-3b205cefa051.PNG)

**Comment by obrie** [comment]
Ran into the same issue -- the problem is documented here: https://github.com/simon-weber/gmusicapi/issues/530

Rather than rely on `nid`, the script should be updated to use `storeId`.  I made this change and the playlists started getting populated again.

**Comment by fox365** [comment]
It looks like nid and storeId have the same syntax, did you just swap them in the script or does it require any other modifications?

**Comment by obrie** [comment]
Just swapped them -- that's it! :smile:

**Comment by fox365** [comment]
Ok, I'll have to start fresh and try again. I made the swap but, I got the
same empty playlists.

**Comment by fox365** [comment]
ner
